# Generated by Django 5.0.6 on 2024-06-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_usuarios_delete_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Persona',
        ),
    ]
