# Generated by Django 5.0.6 on 2024-06-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_rename_usuarios_persona'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Registro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
