# Generated by Django 5.0.6 on 2024-06-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_rename_persona_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
