# Generated by Django 5.0.6 on 2024-06-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='cart.cartitem')),
            ],
        ),
    ]
