# Generated by Django 5.0.6 on 2024-06-29 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='productos',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='BoletaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cart.boleta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
            ],
        ),
    ]
