# Generated by Django 5.0.6 on 2024-06-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_boleta_productos_alter_boleta_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='session_key',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
