# Generated by Django 5.0.6 on 2024-06-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_boleta_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='session_key',
        ),
        migrations.AddField(
            model_name='boletadetalle',
            name='session_key',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
